#include "emit.h"
#include "ast.h"
#include <stdlib.h>

int STRING_COUNT = 0; // global variable for count of strings

void EMIT(ASTnode * p, FILE * fp){

    if(p == NULL) return;
    if(fp == NULL) return;
    
    fprintf(fp, "# MIPS code generated by Compilers class\n\n");
    fprintf(fp, ".data\n\n");
    EMIT_STRINGS(p, fp);
    fprintf(fp, ".align 2\n");
    EMIT_GLOBALS(p, fp);
    fprintf(fp, ".text\n");
    //EMIT_AST(p, fp);



}


void EMIT_GLOBALS(ASTnode * p, FILE * fp){
    while (p){
        if (p->symbol->level == 0 && p->type == A_VARDEC){
            fprintf(fp, "%s: .space %d\n", p->name, p->symbol->mysize*W_SIZE);
			ASTnode * varList = p->s1;
            while(varList){
                fprintf(fp, "%s: .space %d\n", varList->name, varList->symbol->mysize*W_SIZE);
                varList = varList->s1;
            }

        }
        p = p->next;
    }
}

void EMIT_STRINGS(ASTnode * p, FILE * fp){
    if(p == NULL) return;

    if (p->type == A_WRITE && p->name != NULL){
        p->label = CreateLabel();
        fprintf(fp, "%s: .asciiz %s\n", p->label, p->name);
    }

    EMIT_STRINGS(p->next, fp);
    EMIT_STRINGS(p->s1, fp);
    EMIT_STRINGS(p->s2, fp);
}

char * CreateLabel()
{
    char hold[100];
    char *s;
    sprintf(hold,"_L%d",STRING_COUNT);
    s=strdup(hold);
    STRING_COUNT++;
    return (s);
}