#include "emit.h"
#include "ast.h"
#include <stdlib.h>

int STRING_COUNT = 0; // global variable for count of strings

void EMIT(ASTnode * p, FILE * fp){

    if(p == NULL) return;
    if(fp == NULL) return;
    
    fprintf(fp, "# MIPS code generated by Compilers class\n\n");
    fprintf(fp, ".data\n\n");
    EMIT_STRINGS(p, fp);
    fprintf(fp, ".align 2\n");
    EMIT_GLOBALS(p, fp);
    fprintf(fp, ".text\n\n\n");
    EMIT_AST(p, fp);

}


void EMIT_GLOBALS(ASTnode * p, FILE * fp){
    while (p){
        if (p->type == A_VARDEC && p->symbol->level == 0){
            fprintf(fp, "%s: .space %d\n", p->name, p->symbol->mysize*W_SIZE);
			ASTnode * varList = p->s1;
            while(varList){
                fprintf(fp, "%s: .space %d\n", varList->name, varList->symbol->mysize*W_SIZE);
                varList = varList->s1;
            }

        }
        p = p->next;
    }
}

void EMIT_STRINGS(ASTnode * p, FILE * fp){
    if(p == NULL) return;

    if (p->type == A_WRITE && p->name != NULL){
        p->label = CreateLabel();
        fprintf(fp, "%s: .asciiz %s\n", p->label, p->name);
    }

    EMIT_STRINGS(p->next, fp);
    EMIT_STRINGS(p->s1, fp);
    EMIT_STRINGS(p->s2, fp);
}

void EMIT_AST(ASTnode * p, FILE * fp){
    if(p == NULL)
        return;
    
    switch (p->type){

        case A_VARDEC:
            EMIT_AST(p->next, fp);
            break;
        
        case A_FUNCTIONDEC:
            emit_function(p, fp);
            EMIT_AST(p->next, fp);
            break;


        default:
            printf("EMIT_AST case %d not implemented\n", p->type);
            printf("WE SHOULD NEVER BE HERE\n");
            exit(1);
    }
}


char * CreateLabel()
{
    char hold[100];
    char *s;
    sprintf(hold,"_L%d",STRING_COUNT);
    s=strdup(hold);
    STRING_COUNT++;
    return (s);
}

void emit_function(ASTnode * p, FILE * fp){

    emit(fp, p->name, "", "function definition");
}


void emit(FILE *fp, char * label, char * command, char * comment)
{
    if (strcmp("", comment) == 0 ) 
        if (strcmp("",label) == 0)
            fprintf (fp,"\t%s\t\t\n", command );
        else
            fprintf(fp,"%s:\t%s\t\t\n",label, command);
    else
        if (strcmp("",label) == 0)
            fprintf(fp,"\t%s\t\t# %s\n", command, comment);
        else
            fprintf(fp,"%s:\t%s\t\t# %s\n",label, command, comment);
}