# MIPS code generated by Compilers class

.data

_L0: .asciiz "hello\n"
_L1: .asciiz "world\n"
_L2: .asciiz "\n"
_L3: .asciiz "enter a number "
_L4: .asciiz "you entered: "
_L5: .asciiz "\n"
_L6: .asciiz "\n"
.align 2
y: .space 4
Z: .space 400
.text


main:			# function definition
	move $a1, $sp		# Activation Record carve out copy SP
	subi $a1, $a1, 12		# Activation Record carve out copy size of function
	sw $ra, ($a1)		# Store Return address 
	sw $sp 4($a1)		# Store the old Stack pointer
	move $sp, $a1		# Make SP the current activation record


	la $a0, _L0		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	la $a0, _L1		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	li $a0, 123		# expression is a constant
	li $v0, 1		# About to print a number
	syscall		# call write number


	la $a0, _L2		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	la $a0, _L3		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	la $a0, y		# EMIT Var global variable
	li $v0, 5		# About to read a value
	syscall		# read in value $v0 now has the read value
	sw $v0 ($a0)		# store read in value to memory


	la $a0, _L4		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	la $a0, y		# EMIT Var global variable
	lw $a0, ($a0)		# Expression is a VAR
	li $v0, 1		# About to print a number
	syscall		# call write number


	la $a0, _L5		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	la $a0, y		# EMIT Var global variable
	addi $a1, $a0, 0		# Load location of variable into $a1
	li $a0, 4		# expression is a constant
	sw $a0 ($a1)		# store read in value to memory
	la $a0, y		# EMIT Var global variable
	lw $a0, ($a0)		# Expression is a VAR
	li $v0, 1		# About to print a number
	syscall		# call write number


	la $a0, _L6		# The string address
	li $v0, 4		# About to print a string
	syscall		# call write string


	lw $ra ($sp)		# restore old environment RA
	lw $sp 4($sp)		# Return from function store SP

	li $v0, 10		# Exit from Main
	syscall		# EXIT everything
